# Generated by Django 4.1.5 on 2023-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0003_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para doção'), ('A', 'Adotado')], default='P', max_length=1),
        ),
    ]
